config/routes.rb
Weekly::Application.routes.draw do
  
  resources :web_seeds do
    member do 
      put 'upvote'
    end
  end

  root to: "home#index"

end

app/models/web_seed.rb
class WebSeed < Ohm::Model
  attribute :url
  attribute :votes
  counter :votes

  index :url

  def to_hash
    super.merge id: id, url: url, votes: votes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/web_seeds_controller.rb
class WebSeedsController < ApplicationController
  respond_to :json

  def index
    render json: sorted_seeds
  end

  def show
    respond_with WebSeed[params[:id]]
  end 

  def create
    new_web_seed = WebSeed.create(params[:web_seed])
    render json: new_web_seed.to_hash
  end 

  def update
    respond_with WebSeed.update(params[:id], params[:web_seed])
  end 

  def destroy
    WebSeed[params[:id]].delete
    render json: sorted_seeds
  end 

  def upvote
    WebSeed[params[:id]].incr(:votes)
    render json: sorted_seeds
  end

  private
  def sorted_seeds
    WebSeed.all.sort_by(:votes, :order => "desc")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_seeds_helper.rb
module WebSeedsHelper
end

app/views/home/index.html.erb
<h1> angular webseed </h1>

<div ng-app="Weekly">
  <div ng-controller="WebSeedCtrl" ng-init="initWebSeeds()">
    <span ng-hide="web_seeds">Loading...</span>

    <form ng-submit="addWebSeed()">
      <input type="text" ng-model="newWebSeed.url" >
      <input type="submit" value="add">
    </form>

    <div data-icon="web_seeds"> ICON </div>

    <ul>
      <li ng-repeat="web_seed in web_seeds">
        <button ng-click="vote(web_seed)">
          {{web_seed.votes}}
        </button>
        {{web_seed.url}} 
        <a href="#/show/{{web_seed.id}}">show</a>
        <button ng-click="deleteWebSeed(web_seed)">Delete</button>
      </li>
    </ul>
  </div>
  <div ng-view></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weekly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/web_seeds/_form.html.erb
<%= form_for(@web_seed) do |f| %>
  <% if @web_seed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_seed.errors.count, "error") %> prohibited this web_seed from being saved:</h2>

      <ul>
      <% @web_seed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.number_field :votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_seeds/edit.html.erb
<h1>Editing web_seed</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_seed %> |
<%= link_to 'Back', web_seeds_path %>

app/views/web_seeds/index.html.erb
<h1> angular webseed </h1>

<div ng-app="Weekly">
  <div ng-controller="WebSeedCtrl">

    <form ng-submit="addWebSeed()">
      <input type="text" ng-model="newWebSeed.url">
      <input type="submit" value="add">
    </form>

    <ul>
      <li ng-repeat="web_seed in web_seeds">
        {{web_seed.url}}
      </li>
    </ul>
  </div>
</div>

app/views/web_seeds/new.html.erb
<h1>New web_seed</h1>

<%= render 'form' %>

<%= link_to 'Back', web_seeds_path %>

app/views/web_seeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @web_seed.url %>
</p>

<p>
  <b>Votes:</b>
  <%= @web_seed.votes %>
</p>


<%= link_to 'Edit', edit_web_seed_path(@web_seed) %> |
<%= link_to 'Back', web_seeds_path %>